services:
  - type: web
    name: maria-victoria-seoane-front
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_FRONTEND_URL
        sync: false
      - key: NEXT_PUBLIC_MERCADOPAGO_PUBLIC_KEY
        sync: false
